2018-05-09 22:42:21,272 ERROR: Exception on /reset_password_request [POST] [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/routes.py", line 192, in reset_password_request
    send_password_reset_email(user)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/email.py", line 20, in send_password_reset_email
    user=user, token=token))
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/email.py", line 10, in send_email
    mail.send(msg)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "/usr/lib/python3.6/smtplib.py", line 730, in login
    raise last_exception
  File "/usr/lib/python3.6/smtplib.py", line 721, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.6/smtplib.py", line 642, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (534, b'5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbuc\n5.7.14 L-frS3b-bJZfE-TgehYE1717zz4iuNdYwVduj43nKsIDDK0u0MAJZ-tP2n4g6iw_oIYw5o\n5.7.14 PCV8QGv8p7kXGcuB2H88YhP0tpFt4pEo0caMqo0aqSzOlmVQXL0WnEBwbWfTN-dfjP2lV9\n5.7.14 5eyqpNF31xTM6Yxd47bV4l0k86_Z9Zj753Knro0TDP7ALMSKrdNGRCy8WzJowqZl5CbdjU\n5.7.14 dyxXof4SJOgT4W3XDxved0lYuqWxU> Please log in via your web browser and\n5.7.14 then try again.\n5.7.14  Learn more at\n5.7.14  https://support.google.com/mail/answer/78754 e139-v6sm8497692ite.1 - gsmtp')
2018-05-09 22:43:19,506 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:37]
2018-05-10 17:02:54,065 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:37]
2018-05-10 17:03:12,423 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:37]
2018-05-10 17:03:19,469 INFO: Microblog startup [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/__init__.py:37]
2018-05-10 17:03:21,650 ERROR: Exception on /login [GET] [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/routes.py", line 65, in login
    return render_template('login.html',title = 'Sign In', form = form)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
2018-05-10 17:03:21,863 ERROR: Exception on /login [GET] [in /home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/routes.py", line 65, in login
    return render_template('login.html',title = 'Sign In', form = form)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/nicknagi/PycharmProjects/Flask-Micro-Blog/venv/lib/python3.6/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: bootstrap/wtf.html
